import type { Opportunity, FounderProfile } from "@/lib/types";

export const defaultProfile: FounderProfile = {
  name: "Alex Morgan",
  location: "San Francisco, CA",
  stage: "Pre-seed",
  sectors: "AI, climate tech",
  project: "Building an AI copilot that helps small farms reduce water use and forecast crop stress.",
  weeklyHours: 8,
};

export const demoOpportunities: Opportunity[] = [
  {
    id: "nsf-seed-fund",
    name: "America’s Seed Fund",
    type: "Grant",
    organizer: "National Science Foundation",
    description: "Non-dilutive R&D funding for early-stage startups commercializing deep technology.",
    sourceUrl: "https://seedfund.nsf.gov/",
    location: "United States",
    eligibility: "U.S.-based small businesses developing novel, research-driven technology.",
    deadline: null,
    effortHours: 24,
    funding: "Non-dilutive funding",
    tags: ["Deep tech", "Climate", "Research"],
    demo: true,
  },
  {
    id: "aws-activate",
    name: "AWS Activate",
    type: "Startup program",
    organizer: "Amazon Web Services",
    description: "Startup support program with cloud credits, technical guidance, and business resources.",
    sourceUrl: "https://aws.amazon.com/activate/",
    location: "Global",
    eligibility: "Eligible startups, often through an Activate Provider or the self-funded path.",
    deadline: null,
    effortHours: 3,
    funding: "AWS credits",
    tags: ["Cloud credits", "All sectors", "Startup"],
    demo: true,
  },
  {
    id: "techstars-programs",
    name: "Techstars accelerators",
    type: "Accelerator",
    organizer: "Techstars",
    description: "Mentor-driven accelerator programs for early-stage founders; cohort and location vary by program.",
    sourceUrl: "https://www.techstars.com/accelerators",
    location: "Multiple cities / programs",
    eligibility: "Early-stage startups; requirements and investment terms vary by cohort.",
    deadline: null,
    effortHours: 12,
    funding: "Investment; terms vary",
    tags: ["Pre-seed", "Mentorship", "Cohort"],
    demo: true,
  },
  {
    id: "aws-builder-hackathons",
    name: "AWS Builder Center hackathons",
    type: "Hackathon",
    organizer: "AWS Builder Center",
    description: "Browse current builder challenges and hackathons; each event sets its own theme and rules.",
    sourceUrl: "https://builder.aws.com/build/hackathons",
    location: "Online / event-specific",
    eligibility: "Check the individual event page for team, submission, and participation requirements.",
    deadline: null,
    effortHours: 10,
    funding: "Prizes vary by event",
    tags: ["Build", "Online", "AWS"],
    demo: true,
  },
];
